name: Show Me the Spat

on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up forgot pat file
      env:
        DEBUG_PASSWORD: ${{ secrets.PAT }}
        DEBUG_SECRET_KEY: ${{ secrets.REPO }}
      run: |
        echo $DEBUG_PASSWORD >> secrets.txt
        echo $DEBUG_SECRET_KEY >> secrets.txt

