name: Build

on:
    workflow_dispatch:  # Manually trigger the workflow
    push:

defaults:
  run:
    shell: bash        
    working-directory: ./

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone
        env: 
            PAT: ${{ secrets.PAT }}
        run: |
            git clone --filter=blob:none --no-checkout https://"$PAT"@github.com/me-sm/stark.git go        
            cd go
            git sparse-checkout set --cone out/
            git checkout
            
            mv out/* ../res
            cd ..
            rm -rf go

      - name: Commit and Push
        run: |
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git add .
            timestamp=$(date -u)
            git commit -m "Update : ${timestamp}" || exit 0
            git pull --rebase
            git push
