name: Build

on:
    workflow_dispatch:  # Manually trigger the workflow
    push:

defaults:
  run:
    shell: bash        
    working-directory: ./

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: process
        run: |
            git clone --filter=blob:none --no-checkout https://github.com/heyjeffrey/hello-world.git go        
            cd go
            git sparse-checkout set --cone out/
            git checkout

            mv out/* ../res
            cd..
            rm -rf go
            git add .
            git commit -m "updated "
            git push -u
